name: CI Pipeline BE-orders-service

on:
  push:
    branches:
      - develop

jobs:
  build-orders-service-example:
    runs-on: ubuntu-latest
    
    name: Build BE orders-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Grant execute permission for Maven Wrapper
        run: chmod +x ./mvnw

      - name: Install dependencies
        run: ./mvnw dependency:resolve
        
      - name: Grant execute permission for build script
        run: chmod +x .github/scripts/build.sh

      - name: Run build script
        run: |
          ../.github/scripts/build.sh

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-orders-service
          path: ./out
